### ISSUE TITLE
If/else indent

### ISSUE THREAD

**Issue by Shou-nen** [RiFi2k/format-html-in-php#33]
Before:
```
<?php if (1) : ?>
<p class="c1">
<?php else : ?>
<p class="c2">
<?php endif ?>
text
</p>
```

After:
```
<?php if (1) : ?>
<p class="c1">
	<?php else : ?>
	<p class="c2">
		<?php endif ?>
		text
	</p>
```

It doesn't look good.

**Comment by ovidiu-balau** [comment]
Any news on fixing this?

**Comment by RiFi2k** [comment]
@ovidiu-balau So realistically you would use an inline ternary operator in that particular example. The reason the formatting is messed up is because the <p> tags aren't being open and closed properly.

This would be a more realistic example of doing that in the real world.

```php
<p class="<?php echo (1) ? 'c1' : 'c2'; ?>">
text
</p>
```
After
```php
<p class="<?php echo (1) ? 'c1' : 'c2'; ?>">
  text
</p>
```
Which is pretty much as expected. So a more realistic look at the else endif situation would be doing something like this.
```php
<p>
<?php if (1) : ?>
<span class="c1">
hi
</span>
<?php else : ?>
<span class="c2">
hi
</span>
<?php endif ?>
text
</p>
```
After
```php
<p>
  <?php if (1) : ?>
  <span class="c1">
    hi
  </span>
  <?php else : ?>
  <span class="c2">
    hi
  </span>
  <?php endif ?>
  text
</p>
```
Which also comes out as expected.

Feel free to reopen this if you think I'm missing something here, I would be happy to take another look at a different example.
