### ISSUE TITLE
PHP inside <script> breaking

### ISSUE THREAD

**Issue by Sir-Will** [RiFi2k/format-html-in-php#46]
If you have php in a html `<script>` element then it breaks the formatting of it:

![](https://i.imgur.com/zImT4bG.png)

**Comment by elitan** [comment]
Same for me. Everything else works perfectly, however this bug makes the extension unusable for me.

**Comment by elitan** [comment]
Relevant issue: https://github.com/beautify-web/js-beautify/issues/1620

**Comment by elitan** [comment]
For now I added `script` to this setting:

`  "html.format.contentUnformatted": "pre,code,textarea,script"`

**Comment by bitwiseman** [comment]
@Sir-Will 
When reporting formatting issues, providing the actual text instead of an image helps people test fixes. 

@RiFi2k @elitan @Sir-Will 
The reason for this is that, in jsbeautifier templating is turned on by default in HTML and turned off by default in JavaScript.  This was done to limit the potential for breaking changes to existing users. 

I suppose this default should be changed to on by default inside html `<script>` tags, but that is longer term discussion.

The fix is to enble `php` to the settings for jsbeautifier. 

```
{
  "html": {
    "js": {
        "templating": "php"
    }
  }
}
```

Note: even when you do this, the above would still fail because jsbeautifier currently expects [`<?php` or `<?=` to start PHP tags](https://github.com/beautify-web/js-beautify/blob/0500e504796bda1ebd17d4e38ea56387532751d1/test/data/html/tests.js#L2120).  I've opened https://github.com/beautify-web/js-beautify/issues/1840 to track fixing this.  Any help would be much appreciated.
