### ISSUE TITLE
Can't get spaces to work

### ISSUE THREAD

**Issue by DaumantasUrb** [RiFi2k/format-html-in-php#9]
I am trying to use this plugin along with phpfmt. After I save html indentation is changed from spaces to tabs. I want to use 4 spaces. My current config is:
{
    "phpfmt.psr2": true,
    "workbench.colorTheme": "Visual Studio Light",
    "editor.formatOnSave": true,
    "editor.tabSize": 4,
    "editor.insertSpaces": true,
    "editor.detectIndentation": false,
    "window.zoomLevel": 1
}

**Comment by RiFi2k** [comment]
I normally use tabs on PHP but I just switched to try out 4 spaces and it worked straight away for me with this config.

```
{
  "editor.tabSize": 4,
  "editor.insertSpaces": true,
  "editor.detectIndentation": false,
  "editor.formatOnPaste": true,
  "editor.formatOnSave": true,
  "html.format.endWithNewline": true,
  "html.format.wrapLineLength": 0,
  "html.format.indentInnerHtml": false,
  "html.format.wrapAttributes": "force",
  "html.format.indentHandlebars": true,
  "php.suggest.basic": false,
  "phpcs.autoConfigSearch": true,
  "phpcs.showSources": true,
  "phpcs.executablePath": "./vendor/bin/phpcs",
  "phpcbf.autoConfigSearch": true,
  "phpcbf.executablePath": "./vendor/bin/phpcbf",
  "intelephense.formatProvider.enable": false,
  "[php]": {
    "editor.insertSpaces": true
  }
}
```

I left alot of my other settings so you could see I needed to disable Intelephense because it wants to format as well. Also I use PHPCBF for formatting.

But this config works for 4 spaces for sure.
